.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015-2016 Tim Dengel <tim.dengel.debian@gmail.com>,
.\"
.TH GNOME-TWITCH 1 "April 08, 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gnome-twitch \- GNOME Twitch app for watching Twitch.tv streams without a browser or flash.
.SH SYNOPSIS
.B gnome-twitch
.RI [ options ] 
.SH DESCRIPTION
gnome-twitch provides a GTK3 interface for viewing streams on Twitch.
.br
At the moment you can
.br
* browse popular streams,
.br
* browse streams by game,
.br
* search for streams,
.br
* view streams,
.br
* use the chat with a Twitch account,
.br
* change the video quality and
.br
* mark streams as favorites for faster access.
.br
More features like recording streams, VODs (Video-On-Demand), other player backends and integration of Twitch account features like following streams are planned.
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-l, \-\-log\-level=\fILevel\fP
Set logging level. 
.br 
.I Level
can be one of the following numbers:
.br
0 (Critical) 
.br
1 (Warning) 
.br
2 (Message)
.br
3 (Info)
.br
4 (Debug)
